### ISSUE TITLE
Compilation error, cosmology

### ISSUE THREAD

**Issue by mohsensadr** [IPPL-framework/ippl#312]
After the merge of cosmology's branch into IPPL's master, I get this error when I try to compile OPAL-X with the IPPL's master

```
[ 11%] Building CXX object _deps/ippl-build/cosmology/CMakeFiles/StructureFormation.dir/StructureFormation.cpp.o
/psi/home/sadr_m/opal-x/downloads/opal-x/build_openmp/_deps/ippl-src/cosmology/StructureFormation.cpp:33:10: fatal error: Ippl.h: No such file or directory
   33 | #include "Ippl.h"
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [_deps/ippl-build/cosmology/CMakeFiles/StructureFormation.dir/StructureFormation.cpp.o] Error 1
make[1]: *** [_deps/ippl-build/cosmology/CMakeFiles/StructureFormation.dir/all] Error 2
```

I'm not sure what the issue is. Can we change the CMakeList of IPPL such that cosmology option is set to OFF by default?

https://github.com/IPPL-framework/ippl/blob/8c2c2590f8b6c87dc285d95109c960e0f73fe23f/CMakeLists.txt#L233C1-L243C9

**Comment by aaadelmann** [comment]
I agree cosmology option should be set OFF as default.

**Comment by aaadelmann** [comment]
will fix this now
