### PR TITLE
Propagate (default) `Kokkos_VERSION` to `Kokkos_VERSION_GIT`

### LINKED ISSUE #524: Default Kokkos (`5.1.1`) is not fetched
OPALX's `cmake` log says (when compiling without any explicit `-DKokkos_VERSION`):
```
Cloning into 'kokkos-src'...
Switched to a new branch 'master'
branch 'master' set up to track 'origin/master'.
-- Setting default Kokkos CXX standard to 20
-- Kokkos version: 4.7.1
-- The project name is: Kokkos
```
IPPL defaults `Kokkos_VERSION_DEFAULT` to `5.1.1`, but that is only used for `find_package(Kokkos 5.1.1 ...)`. If no installed Kokkos is found, IPPL only sets a git tag when `Kokkos_VERSION` has the form `git.<tag>`. Since default `5.1.1` is not `git.5.1.1`, `KOKKOS_VERSION_GIT` is empty, so this line effectively fetches Kokkos with no explicit tag:
```cmake
FetchContent_Declare(Kokkos GIT_TAG ${KOKKOS_VERSION_GIT} GIT_REPOSITORY ${Kokkos_REPOSITORY})
```
CMake then defaults the missing `GIT_TAG` to master.

I would suggest propagating "5.1.1" also to `KOKKOS_VERSION_GIT`, such that the fetched Kokkos matches the requested version.

### PR DESCRIPTION
**Pull request by aliemen**
closes #524 

The fix is simple: if no version is provided (default behaviour) and no compatible local source is found, build it from source with the default version instead of an empty git tag defaulting to "master". Now, e.g. the OPALX cmake shows:
```
-- Fetching IPPL ref: 524-default-kokkos-511-is-not-fetched
-- IPPL shallow fetch: TRUE
-- Build type is: Release
Cloning into 'ippl-src'...
Switched to a new branch '524-default-kokkos-511-is-not-fetched'
branch '524-default-kokkos-511-is-not-fetched' set up to track 'origin/524-default-kokkos-511-is-not-fetched'.
-- 📦 Configuring IPPL Version: 3.2 : "IPPL v3.2"
-- 🔧IPPL will be built as a STATIC library
-- Build type is: Release
-- ✅ Project setup complete
-- ✅ Compiler options configured
-- ✅ MPI found 3.1
-- ✅ Kokkos 5.1.1 building from source
-- IPPL_PLATFORM set: Kokkos_ENABLE_SERIAL 'ON'
-- IPPL_PLATFORM set: Kokkos_ENABLE_OPENMP 'OFF'
-- IPPL_PLATFORM set: Kokkos_ENABLE_CUDA 'OFF'
-- IPPL_PLATFORM set: Kokkos_ENABLE_HIP 'OFF'
-- IPPL_PLATFORM set: Kokkos_ENABLE_SYCL 'OFF'
Cloning into 'kokkos-src'...
HEAD is now at 267ebc25f Reference to SLSA GitHub Generator by tag instead of digest
-- Setting default Kokkos CXX standard to 20
-- Kokkos version: 5.1.1
-- The project name is: Kokkos
-- Configured git information in /Users/aliemen/Desktop/opalx/buildtest/_deps/ippl-build/_deps/kokkos-build/generated/Kokkos_Version_Info.cpp
-- Kokkos is configured for CMake languages CXX compilation (using Clang version 21.1.8)
-- Using -std=c++20 for C++20 standard as feature
-- Built-in Execution Spaces:
--     Device Parallel: NoTypeDefined
--     Host Parallel: NoTypeDefined
--       Host Serial: SERIAL
```
Before it would always say "`Kokkos version: 4.7.01`".

### CODE REVIEW

**Review by aaadelmann — APPROVED** [review]

**Comment by aliemen** [comment]
Looks like the newest Kokkos `5.1.1` doesn't compile with the `cuda/12.9` on Daint. CI passes, since cscs ci specifically pins `Kokkos_VERSION=git.4.7.02`, but OPALX doesn't compile, see log below.

I suggest keeping Kokkos `5.0.0` for now, since it works perfectly fine everywhere where I tested it (Gwendolen with the new toolchain, Daint, locally on CPU). 

---

```text
.../cuda-daint/build/_deps/ippl-build/_deps/kokkos-src/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(115): error: namespace "desul" has no member "atomic_mod"
  template<class T> __attribute__((device)) __attribute__((host)) Impl::enable_if_atomic_t<T, void> atomic_mod(T* ptr, Impl::not_deduced_atomic_t<T> val) { desul::atomic_mod(const_cast<std::remove_volatile_t<T>*>(ptr), val, desul::MemoryOrderRelaxed(), desul::MemoryScopeDevice()); }
                                                                                                                                                                   ^

.../cuda-daint/build/_deps/ippl-build/_deps/kokkos-src/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(116): error: namespace "desul" has no member "atomic_and"
  template<class T> __attribute__((device)) __attribute__((host)) Impl::enable_if_atomic_t<T, void> atomic_and(T* ptr, Impl::not_deduced_atomic_t<T> val) { desul::atomic_and(const_cast<std::remove_volatile_t<T>*>(ptr), val, desul::MemoryOrderRelaxed(), desul::MemoryScopeDevice()); }
                                                                                                                                                                   ^

.../cuda-daint/build/_deps/ippl-build/_deps/kokkos-src/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(117): error: namespace "desul" has no member "atomic_or"
  template<class T> __attribute__((device)) __attribute__((host)) Impl::enable_if_atomic_t<T, void> atomic_or (T* ptr, Impl::not_deduced_atomic_t<T> val) { desul::atomic_or (const_cast<std::remove_volatile_t<T>*>(ptr), val, desul::MemoryOrderRelaxed(), desul::MemoryScopeDevice()); }
                                                                                                                                                                   ^

.../cuda-daint/build/_deps/ippl-build/_deps/kokkos-src/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(118): error: namespace "desul" has no member "atomic_xor"
  template<class T> __attribute__((device)) __attribute__((host)) Impl::enable_if_atomic_t<T, void> atomic_xor(T* ptr, Impl::not_deduced_atomic_t<T> val) { desul::atomic_xor(const_cast<std::remove_volatile_t<T>*>(ptr), val, desul::MemoryOrderRelaxed(), desul::MemoryScopeDevice()); }
                                                                                                                                                                   ^

.../cuda-daint/build/_deps/ippl-build/_deps/kokkos-src/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(119): error: namespace "desul" has no member "atomic_nand"
  template<class T> __attribute__((device)) __attribute__((host)) Impl::enable_if_atomic_t<T, void> atomic_nand(T* ptr, Impl::not_deduced_atomic_t<T> val) { desul::atomic_nand(const_cast<std::remove_volatile_t<T>*>(ptr), val, desul::MemoryOrderRelaxed(), desul::MemoryScopeDevice()); }
                                                                                                                                                                    ^

.../cuda-daint/build/_deps/ippl-build/_deps/kokkos-src/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(120): error: namespace "desul" has no member "atomic_lshift"
  template<class T> __attribute__((device)) __attribute__((host)) Impl::enable_if_atomic_t<T, void> atomic_lshift(T* ptr, Impl::not_deduced_atomic_t<T> val) { desul::atomic_lshift(const_cast<std::remove_volatile_t<T>*>(ptr), val, desul::MemoryOrderRelaxed(), desul::MemoryScopeDevice()); }
                                                                                                                                                                      ^

.../cuda-daint/build/_deps/ippl-build/_deps/kokkos-src/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(121): error: namespace "desul" has no member "atomic_rshift"
  template<class T> __attribute__((device)) __attribute__((host)) Impl::enable_if_atomic_t<T, void> atomic_rshift(T* ptr, Impl::not_deduced_atomic_t<T> val) { desul::atomic_rshift(const_cast<std::remove_volatile_t<T>*>(ptr), val, desul::MemoryOrderRelaxed(), desul::MemoryScopeDevice()); }
                                                                                                                                                                      ^

.../cuda-daint/build/_deps/ippl-build/_deps/kokkos-src/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(115): error: namespace "desul" has no member "atomic_mod"
  template<class T> __attribute__((device)) __attribute__((host)) Impl::enable_if_atomic_t<T, void> atomic_mod(T* ptr, Impl::not_deduced_atomic_t<T> val) { desul::atomic_mod(const_cast<std::remove_volatile_t<T>*>(ptr), val, desul::MemoryOrderRelaxed(), desul::MemoryScopeDevice()); }
                                                                                                                                                                   ^

.../cuda-daint/build/_deps/ippl-build/_deps/kokkos-src/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(116): error: namespace "desul" has no member "atomic_and"
  template<class T> __attribute__((device)) __attribute__((host)) Impl::enable_if_atomic_t<T, void> atomic_and(T* ptr, Impl::not_deduced_atomic_t<T> val) { desul::atomic_and(const_cast<std::remove_volatile_t<T>*>(ptr), val, desul::MemoryOrderRelaxed(), desul::MemoryScopeDevice()); }
                                                                                                                                                                   ^

.../cuda-daint/build/_deps/ippl-build/_deps/kokkos-src/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(117): error: namespace "desul" has no member "atomic_or"
  template<class T> __attribute__((device)) __attribute__((host)) Impl::enable_if_atomic_t<T, void> atomic_or (T* ptr, Impl::not_deduced_atomic_t<T> val) { desul::atomic_or (const_cast<std::remove_volatile_t<T>*>(ptr), val, desul::MemoryOrderRelaxed(), desul::MemoryScopeDevice()); }
                                                                                                                                                                   ^

.../cuda-daint/build/_deps/ippl-build/_deps/kokkos-src/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(118): error: namespace "desul" has no member "atomic_xor"
  template<class T> __attribute__((device)) __attribute__((host)) Impl::enable_if_atomic_t<T, void> atomic_xor(T* ptr, Impl::not_deduced_atomic_t<T> val) { desul::atomic_xor(const_cast<std::remove_volatile_t<T>*>(ptr), val, desul::MemoryOrderRelaxed(), desul::MemoryScopeDevice()); }
                                                                                                                                                                   ^

.../cuda-daint/build/_deps/ippl-build/_deps/kokkos-src/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(119): error: namespace "desul" has no member "atomic_nand"
  template<class T> __attribute__((device)) __attribute__((host)) Impl::enable_if_atomic_t<T, void> atomic_nand(T* ptr, Impl::not_deduced_atomic_t<T> val) { desul::atomic_nand(const_cast<std::remove_volatile_t<T>*>(ptr), val, desul::MemoryOrderRelaxed(), desul::MemoryScopeDevice()); }
                                                                                                                                                                    ^

.../cuda-daint/build/_deps/ippl-build/_deps/kokkos-src/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(120): error: namespace "desul" has no member "atomic_lshift"
  template<class T> __attribute__((device)) __attribute__((host)) Impl::enable_if_atomic_t<T, void> atomic_lshift(T* ptr, Impl::not_deduced_atomic_t<T> val) { desul::atomic_lshift(const_cast<std::remove_volatile_t<T>*>(ptr), val, desul::MemoryOrderRelaxed(), desul::MemoryScopeDevice()); }
                                                                                                                                                                      ^

.../cuda-daint/build/_deps/ippl-build/_deps/kokkos-src/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(121): error: namespace "desul" has no member "atomic_rshift"
  template<class T> __attribute__((device)) __attribute__((host)) Impl::enable_if_atomic_t<T, void> atomic_rshift(T* ptr, Impl::not_deduced_atomic_t<T> val) { desul::atomic_rshift(const_cast<std::remove_volatile_t<T>*>(ptr), val, desul::MemoryOrderRelaxed(), desul::MemoryScopeDevice()); }
```

**Comment by aaadelmann** [comment]
agree 5.0.0

**Comment by aliemen** [comment]
Looks like GitHub actions [are down right now](https://www.githubstatus.com/incidents/gnftqj9htp0g). Will restart the tests later.
